import {
  LayoutDashboard,
  ShoppingBag,
  Package,
  Heart,
  MapPin,
  Bell,
  Ticket,
  Star,
  Settings,
  User,
  BarChart3,
  Boxes,
  Truck,
  Wallet,
  Store,
  Users,
  Shield,
  FileText,
  Image,
  MessageSquare,
  FolderTree,
} from 'lucide-react';

export const customerNav = [
  { to: '', label: 'Dashboard', icon: LayoutDashboard, end: true },
  { to: '/orders', label: 'Orders', icon: ShoppingBag },
  { to: '/wishlist', label: 'Wishlist', icon: Heart },
  { to: '/cart', label: 'Cart', icon: Package },
  { to: '/addresses', label: 'Addresses', icon: MapPin },
  { to: '/notifications', label: 'Notifications', icon: Bell },
  { to: '/coupons', label: 'Coupons', icon: Ticket },
  { to: '/reviews', label: 'Reviews', icon: Star },
  { to: '/profile', label: 'Profile', icon: User },
  { to: '/settings', label: 'Settings', icon: Settings },
];

export const sellerNav = [
  { to: '', label: 'Dashboard', icon: LayoutDashboard, end: true },
  { to: '/analytics', label: 'Analytics', icon: BarChart3 },
  { to: '/orders', label: 'Orders', icon: ShoppingBag },
  { to: '/products', label: 'Products', icon: Package },
  { to: '/inventory', label: 'Inventory', icon: Boxes },
  { to: '/reviews', label: 'Reviews', icon: Star },
  { to: '/coupons', label: 'Coupons', icon: Ticket },
  { to: '/store', label: 'Store', icon: Store },
  { to: '/wallet', label: 'Wallet', icon: Wallet },
  { to: '/transactions', label: 'Transactions', icon: FileText },
  { to: '/shipping', label: 'Shipping', icon: Truck },
  { to: '/notifications', label: 'Notifications', icon: Bell },
  { to: '/profile', label: 'Profile', icon: User },
  { to: '/settings', label: 'Settings', icon: Settings },
];

export const adminNav = [
  { to: '', label: 'Dashboard', icon: LayoutDashboard, end: true },
  { to: '/users', label: 'Users', icon: Users },
  { to: '/sellers', label: 'Sellers', icon: Store },
  { to: '/products', label: 'Products', icon: Package },
  { to: '/orders', label: 'Orders', icon: ShoppingBag },
  { to: '/transactions', label: 'Transactions', icon: FileText },
  { to: '/analytics', label: 'Analytics', icon: BarChart3 },
  { to: '/reports', label: 'Reports', icon: BarChart3 },
  { to: '/categories', label: 'Categories', icon: FolderTree },
  { to: '/coupons', label: 'Coupons', icon: Ticket },
  { to: '/cms', label: 'CMS', icon: FileText },
  { to: '/banners', label: 'Banners', icon: Image },
  { to: '/notifications', label: 'Notifications', icon: Bell },
  { to: '/support', label: 'Support', icon: MessageSquare },
  { to: '/reviews', label: 'Reviews', icon: Star },
  { to: '/settings', label: 'Settings', icon: Shield },
];
